server {
  listen 80;
  server_name localhost tp-performances www.tp-performances;
 
  root /var/www/tp-performances;
  index index.php index.html;
 
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }
 
  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_read_timeout 300;
  }
 
  location ~* \.(svg|gif|otf|jpg|jpeg|png|css|js|ttf)$ {
    add_header Cache-Control "max-age=0, must-revalidate, public";
    add_header Pragma public;
    add_header Vary Accept-Encoding;
  }
}